---
title: "Project Graphs"
output: github_document
date: "2025-04-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r load-packages, message=FALSE}
library(tidyverse)
library(openintro)
library(ggplot2)
library(scales)
library(plotly)
library(readxl)
library(usmap)
library(janitor)
```

```{r}
StateLevelDebt <- read_excel("Project Data Sets/State Level Debt/StateLevelDebt.xlsx")
names(StateLevelDebt) <- gsub(" ", "_", names(StateLevelDebt))
names(StateLevelDebt)
names(StateLevelDebt) <- gsub(",", "", names(StateLevelDebt))
names(StateLevelDebt)
```

```{r}
state_data <- StateLevelDebt |>
  rename(
    State_name = State_Name,
    S_Abbreviation = State_Abbreviation,
    FIPS = State_FIPS,
    
    AnyDebt_All = Share_with_any_debt_in_collections_All,
    AnyDebt_Color = Share_with_any_debt_in_collections_Comm_of_color,
    AnyDebt_White = Share_with_any_debt_in_collections_White_comm,
    
    MedianDebt_All = Median_debt_in_collections_All,
    MedianDebt_Color = Median_debt_in_collections_Comm_of_color,
    MedianDebt_White = Median_debt_in_collections_White_comm,
    
    MedDebt_All = Share_with_medical_debt_in_collections_All,
    MedDebt_Color = Share_with_medical_debt_in_collections_Comm_of_color,
    MedDebt_White = Share_with_medical_debt_in_collections_White_comm,
    
    StudentLoanDefault_All = Share_of_student_loan_holders_with_student_loan_debt_in_default_All,
    StudentLoanDefault_Color = Share_of_student_loan_holders_with_student_loan_debt_in_default_Comm_of_color,
    StudentLoanDefault_White = Share_of_student_loan_holders_with_student_loan_debt_in_default_White_comm,
    
    AutoRetailDelinq_All = `Auto/retail_loan_delinquency_rate_All`,
    AutoRetailDelinq_Color = `Auto/retail_loan_delinquency_rate_Comm_of_color`,
    AutoRetailDelinq_White = `Auto/retail_loan_delinquency_rate_White_comm`,
    
    CreditCardDelinq_All = Credit_card_debt_delinquency_rate_All,
    CreditCardDelinq_Color = Credit_card_debt_delinquency_rate_Comm_of_color,
    CreditCardDelinq_White = Credit_card_debt_delinquency_rate_White_comm,
    
    CreditCardDebt_All = Median_credit_card_delinquent_debt_All,
    CreditCardDebt_Color = Median_credit_card_delinquent_debt_Comm_of_color,
    CreditCardDebt_White = Median_credit_card_delinquent_debt_White_comm,
    
    Percent_POC = Share_of_people_of_color,
    
    Income_All = Average_household_income_All,
    Income_Color = Average_household_income_Comm_of_color,
    Income_White = Average_household_income_White_comm
  )
```

### Per state POC and and debt

```{r}
state_data <- state_data |>
  mutate(
    Percent_POC = as.numeric(Percent_POC),
    Percent_POC = ifelse(Percent_POC > 1, Percent_POC / 100, Percent_POC),
    AnyDebt_C_Percent = as.numeric(AnyDebt_Color),
    AnyDebt_C_Percent = ifelse(AnyDebt_C_Percent > 1, AnyDebt_C_Percent / 100, AnyDebt_C_Percent),
    label_text = paste0(
      "State: ", State_name, "<br>",
      "POC: ", percent(Percent_POC, accuracy = 0.1), "<br>",
      "Debt: ", percent(AnyDebt_C_Percent, accuracy = 0.1)
      )
  )
    
p <- ggplot(state_data, aes(
  x = Percent_POC, 
  y = AnyDebt_C_Percent,
  text = label_text)) +
  geom_point(size = 3, alpha = 0.7, stroke = .7, shape = 21, fill = "lightpink", color = "black") +
  scale_x_continuous(labels = percent_format(accuracy = .1),
                     breaks = seq(0, 1, by = 0.1)) +
  scale_y_continuous(labels = percent_format(accuracy = .1),
                     breaks = seq(0, 0.5, by = 0.05))+
  labs(
    title = "Percent of POC vs. Share with Any Debt",
    x = "Percent People of Color",
    y = "Share with Any Debt"
  ) +
  theme_minimal()

ggplotly(p, tooltip = "text")
```

#Per state boxplot

```{r}
state_data <- state_data |>
  mutate(
    loan_all = as.numeric(StudentLoanDefault_All),
    loan_all = ifelse(loan_all > 1, loan_all / 100, loan_all),
    loan_white = as.numeric(StudentLoanDefault_White),
    loan_white = ifelse(loan_white > 1, loan_white / 100, loan_white),
    loan_colored = as.numeric(StudentLoanDefault_Color),
    loan_colored = ifelse(loan_colored > 1, loan_colored / 100, loan_colored)
  )

loan_long <- state_data %>%
  select(State_name, loan_all, loan_white, loan_colored) %>%
  pivot_longer(
    cols = starts_with("loan_"),
    names_to = "Group",
    values_to = "DefaultRate"
  )

main_groups <- c("loan_white", "loan_colored", "loan_all")

main_data <- loan_long %>%
  filter(Group %in% main_groups) %>%
  mutate(
    DefaultRatePercent = DefaultRate * 100,
    Group = factor(Group,
                   levels = c("loan_white", "loan_colored", "loan_all"),
                   labels = c("White", "People of Color", "All")))

extra_data <- loan_long %>%
  filter(!(Group %in% main_groups)) %>%
  mutate(DefaultRatePercent = DefaultRate * 100)

p_1 <- ggplot() +
  geom_boxplot(data = main_data,
               aes(x = Group, y = DefaultRatePercent, fill = Group), alpha = 0.7) +
  geom_jitter(data = extra_data,
              aes(x = "Other", y = DefaultRatePercent,
                  text = paste("Group:", Group, "<br>Default Rate:", percent(DefaultRatePercent, 0.1))),
              color = "red", size = 2, width = 0.2, alpha = 0.8) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  theme_minimal() +
  labs(
    title = "Distribution of Student Loan Default Rates by Group",
    x = "Group",
    y = "Default Rate (%)",
    fill = "Group"
  )

ggplotly(p_1, tooltip = "text")
```

### Maps 

```{r}
us_states <- us_map(regions = "states")
ggplot(us_states) +
  geom_sf()

my_map_theme <- function(){
theme(panel.background=element_blank(),
axis.text=element_blank(),
axis.ticks=element_blank(),
axis.title=element_blank())
}

us_county <- us_map(regions = "counties")
ggplot(us_county) +
  geom_sf() +
  my_map_theme()
```


### Federal student aid


```{r}
aid_portfolio <- read_excel("Project Data Sets/Federal student aid/aid_portfolio.xlsx", skip = 4)
```

```{r}
colnames(aid_portfolio) <- c(
  "fiscal_year", 
  "quarter", 
  "direct_loans", 
  "direct_loan_recipients", 
  "ffel", 
  "ffel_recipients", 
  "perkins_loans", 
  "perkins_recipients", 
  "total_outstanding", 
  "undup_recipients"
)
aid_portfolio <- aid_portfolio[-c(1, 42, 43, 44, 45), ]
```

```{r}
aid_portfolio <- aid_portfolio |>
  mutate(across(direct_loans:undup_recipients, as.numeric))
```

```{r}
aid_portfolio <- aid_portfolio |>
  fill(fiscal_year, .direction = "down")
```


```{r}
aid_portfolio <- aid_portfolio |>
  mutate(
    period = ifelse(
      is.na(quarter), 
      as.character(fiscal_year),
      paste0(fiscal_year, " ", quarter)
    )
  )
```


```{r}
ggplot(aid_portfolio, aes(x = period, y = direct_loans)) +
  geom_bar(stat = "identity", fill = "grey") +
  labs(title = "Student Direct Loan Recipients by Fiscal Year",
       x = "Fiscal Year",
       y = "Recipients (in millions)") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


## Including Plots

```{r pressure, echo=FALSE}

```


